In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/New Job Descriptions.csv", on_bad_lines='skip', engine='python')

In [5]:
df.shape

(8785, 23)

In [6]:
columns_to_keep = ['Job Id', 'Job Title', 'Company', 'location', 'Job Description', 'Experience', 'Qualifications', 'Salary Range', 'Work Type','skills']
df = df[columns_to_keep]

In [9]:
df.head(10)

,Job Id,Job Title,Company,location,Job Description,Experience,Qualifications,Salary Range,Work Type,skills
0,1.089840e+15,Digital Marketing Specialist,Icahn Enterprises,Douglas,Social Media Managers oversee an organizations...,5 to 15 Years,M.Tech,$59K-$99K,Intern,"Social media platforms (e.g., Facebook, Twitte..."
1,3.984540e+14,Web Developer,PNC Financial Services Group,Ashgabat,Frontend Web Developers design and implement u...,2 to 12 Years,BCA,$56K-$116K,Intern,"HTML, CSS, JavaScript Frontend frameworks (e.g..."
2,4.816400e+14,Operations Manager,United Services Automobile Assn.,Macao,Quality Control Managers establish and enforce...,0 to 12 Years,PhD,$61K-$104K,Temporary,Quality control processes and methodologies St...
3,6.881930e+14,Network Engineer,Hess,Porto-Novo,"Wireless Network Engineers design, implement, ...",4 to 11 Years,PhD,$65K-$91K,Full-Time,Wireless network design and architecture Wi-Fi...
4,1.170580e+14,Event Manager,Cairn Energy,Santiago,A Conference Manager coordinates and manages c...,1 to 12 Years,MBA,$64K-$87K,Intern,Event planning Conference logistics Budget man...
5,1.168310e+14,Software Tester,Adani Ports and Special Economic Zone,Brussels,A Quality Assurance Analyst tests software and...,4 to 12 Years,MCA,$59K-$93K,Full-Time,Quality assurance processes Testing methodolog...
6,1.292170e+15,Teacher,FedEx,George Town,A Classroom Teacher educates students in a spe...,3 to 15 Years,PhD,$63K-$103K,Temporary,Teaching pedagogy Classroom management Curricu...
7,1.498780e+15,UX/UI Designer,Ryder System,SÃ£o TomÃ©,User Interface Designers focus on the visual a...,2 to 8 Years,M.Com,$65K-$102K,Contract,UI design principles and best practices Graphi...
8,1.680290e+15,UX/UI Designer,Zee Entertainment Enterprises,Male,Interaction Designers specialize in designing ...,2 to 9 Years,BBA,$65K-$102K,Temporary,Interaction design principles User behavior an...
9,2.556280e+14,Wedding Planner,CSX,Saint John's,A Wedding Consultant assists couples in planni...,1 to 10 Years,BBA,$60K-$80K,Full-Time,Wedding planning Vendor coordination Event man...

In [13]:
df.to_csv('/content/New Job Descriptions.csv', index=False)

In [14]:
df.isnull().sum()

Job Id             0
Job Title          0
Company            0
location           0
Job Description    0
Experience         0
Qualifications     0
Salary Range       0
Work Type          0
skills             0
dtype: int64