In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/clean_jobs_descriptions_combined (1).csv")

In [4]:
vectorizer = TfidfVectorizer(
    ngram_range=(1, 3),
    stop_words="english",
)

In [6]:
X = vectorizer.fit_transform(df["clean_description"].fillna(""))

terms = vectorizer.get_feature_names_out()
scores = X.mean(axis=0).A1

ngram_df = pd.DataFrame({
    "ngram": terms,
    "tfidf_score": scores
})

ngram_df = ngram_df.sort_values(by="tfidf_score", ascending=False)

ngram_df.head(10)

           ngram  tfidf_score
11646       user     0.016125
2705        data     0.016083
4039      ensure     0.011663
10806    support     0.010763
4568   financial     0.010168
2464      create     0.009974
2992      design     0.009717
8850     provide     0.009579
6565      manage     0.009421
4159    ensuring     0.009194

In [7]:
unigrams = ngram_df[
    ~ngram_df["ngram"].str.contains(" ")
]

unigrams.head(20)

            ngram  tfidf_score
11646        user     0.016125
2705         data     0.016083
4039       ensure     0.011663
10806     support     0.010763
4568    financial     0.010168
2464       create     0.009974
2992       design     0.009717
8850      provide     0.009579
6565       manage     0.009421
4159     ensuring     0.009194
9692        sales     0.008969
9030      quality     0.008853
10942     systems     0.008402
3173      develop     0.008168
6850    marketing     0.008158
8606     products     0.008058
10565  strategies     0.008012
6442     maintain     0.007951
9399     research     0.007889
9882     security     0.007657

In [8]:
bigrams = ngram_df[
    ngram_df["ngram"].str.count(" ") == 1
]

bigrams.head(20)

                       ngram  tfidf_score
10167           social media     0.006412
11655        user experience     0.004182
11850     visually appealing     0.004016
2884         decision making     0.003985
3408      digital interfaces     0.003851
8634       products services     0.003824
11677         user interface     0.003508
10797           supply chain     0.003419
6720        managers oversee     0.003330
231    administrators manage     0.003181
4178           ensuring data     0.002894
8873        provide insights     0.002870
1951       computer networks     0.002716
11663       user experiences     0.002625
3019        design implement     0.002573
2768          data integrity     0.002555
3082        designers create     0.002543
11666          user friendly     0.002513
11886       web applications     0.002509
11674      user interactions     0.002359

In [9]:
trigrams = ngram_df[
    ngram_df["ngram"].str.count(" ") == 2
]

trigrams.head(20)

                                  ngram  tfidf_score
4181            ensuring data integrity     0.002376
7704    organizations computer networks     0.002301
2406          cost saving opportunities     0.002288
3100     designers specialize designing     0.002261
4445       experiences considering user     0.002085
11664      user experiences considering     0.002085
5869       interfaces create meaningful     0.002085
2509         create meaningful engaging     0.002085
11648          user behaviors responses     0.002085
3917          engaging user experiences     0.002085
5840   interaction designers specialize     0.002085
11675         user interactions digital     0.002085
2091         considering user behaviors     0.002085
10365         specialize designing user     0.002085
5843    interactions digital interfaces     0.002085
6961           meaningful engaging user     0.002085
3410          digital interfaces create     0.002085
3127        designing user interactions     0.002085
5281               identify cost saving     0.002015
11856           visually appealing user     0.001969